name: SuperbVote
main: io.minimum.minecraft.superbvote.SuperbVote
author: tuxed
version: ${project.version}
depend: [Votifier]
softdepend: [Vault, PlaceholderAPI]
api-version: "1.19"
commands:
  superbvote:
    description: SuperbVote main command.
    aliases: [sv]
permissions:
  superbvote.notify:
    default: true
  superbvote.votes.others:
    default: op
  superbvote.admin:
    default: op
